### ISSUE TITLE
Custom short url support?

### ISSUE THREAD

**Issue by jahands** [juhohei/shorten#1]
I've been looking for something to use as a local url shortener, which supports custom links.
So things like this:
http://mylocalsite/things/stuff/thing1.html
Can be shortened to something like:
http://mysite/this

Right now I just have nginx rules setup to do 301 redirects.
I don't have much experience with node/iojs, otherwise I'd submit a PR.
Any chance you'd be willing to implement it or point me in the right direction? :)

**Comment by juhohei** [comment]
Sure, I can implement support for custom urls. I'll do it tomorrow.

As you probably noticed, this project uses in-memory "database", so the shortened urls get cleared every time you shut down the server. This is easy to fix: for local usage a flat json file to store the data would be enough, for a more sophisticated solution a NoSQL database should work well.

**Comment by jahands** [comment]
JSON would be really cool! :) I just need it for local stuff so JSON would suffice.

**Comment by juhohei** [comment]
Done. If there are any issues, please report :)
